//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCoreModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCoreModel.Localization.AdminRes", typeof(AdminRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string BUTTON_ADMIN_LINK {
            get {
                return ResourceManager.GetString("BUTTON_ADMIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable account.
        /// </summary>
        public static string BUTTON_DISABLE {
            get {
                return ResourceManager.GetString("BUTTON_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable account.
        /// </summary>
        public static string BUTTON_ENABLE {
            get {
                return ResourceManager.GetString("BUTTON_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string BUTTON_USER_ADMIN_LINK {
            get {
                return ResourceManager.GetString("BUTTON_USER_ADMIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string COLUMN_ACL_USER_ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("COLUMN_ACL_USER_ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string COLUMN_ACL_USER_EMAIL {
            get {
                return ResourceManager.GetString("COLUMN_ACL_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COLUMN_ACL_USER_FULLNAME {
            get {
                return ResourceManager.GetString("COLUMN_ACL_USER_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string COLUMN_ACL_USER_IS_DISABLED {
            get {
                return ResourceManager.GetString("COLUMN_ACL_USER_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territories.
        /// </summary>
        public static string COLUMN_ACL_USER_TERRITORY_COUNT {
            get {
                return ResourceManager.GetString("COLUMN_ACL_USER_TERRITORY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this user account?.
        /// </summary>
        public static string CONFIRM_USER_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to disable this user account?.
        /// </summary>
        public static string CONFIRM_USER_DISABLE {
            get {
                return ResourceManager.GetString("CONFIRM_USER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to enable this user account?.
        /// </summary>
        public static string CONFIRM_USER_ENABLE {
            get {
                return ResourceManager.GetString("CONFIRM_USER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        public static string DETAIL_ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("DETAIL_ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DETAIL_EMAIL {
            get {
                return ResourceManager.GetString("DETAIL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DETAIL_FULLNAME {
            get {
                return ResourceManager.GetString("DETAIL_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DETAIL_IS_DISABLED {
            get {
                return ResourceManager.GetString("DETAIL_IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max territories.
        /// </summary>
        public static string DETAIL_MAX_TERRITORY_COUNT {
            get {
                return ResourceManager.GetString("DETAIL_MAX_TERRITORY_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting user account.
        /// </summary>
        public static string ERROR_USER_DELETE {
            get {
                return ResourceManager.GetString("ERROR_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while disabling user account.
        /// </summary>
        public static string ERROR_USER_DISABLE {
            get {
                return ResourceManager.GetString("ERROR_USER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while enabling user account.
        /// </summary>
        public static string ERROR_USER_ENABLE {
            get {
                return ResourceManager.GetString("ERROR_USER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user account.
        /// </summary>
        public static string MODAL_TITLE_USER_DELETE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable user account.
        /// </summary>
        public static string MODAL_TITLE_USER_DISABLE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_USER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable user account.
        /// </summary>
        public static string MODAL_TITLE_USER_ENABLE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_USER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string PAGE_TITLE_ADMIN {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string PAGE_TITLE_USER_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_USER_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User detail.
        /// </summary>
        public static string PAGE_TITLE_USER_DETAIL {
            get {
                return ResourceManager.GetString("PAGE_TITLE_USER_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string PAGE_TITLE_USER_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_USER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user.
        /// </summary>
        public static string PAGE_TITLE_USER_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_USER_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been deleted.
        /// </summary>
        public static string SUCCESS_USER_DELETE {
            get {
                return ResourceManager.GetString("SUCCESS_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been disabled.
        /// </summary>
        public static string SUCCESS_USER_DISABLE {
            get {
                return ResourceManager.GetString("SUCCESS_USER_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account has been enabled.
        /// </summary>
        public static string SUCCESS_USER_ENABLE {
            get {
                return ResourceManager.GetString("SUCCESS_USER_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already used.
        /// </summary>
        public static string VALIDATION_EMAIL_USED {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_USED", resourceCulture);
            }
        }
    }
}
