//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCoreModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckInRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckInRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCoreModel.Localization.CheckInRes", typeof(CheckInRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        public static string BUTTON_CHECKIN {
            get {
                return ResourceManager.GetString("BUTTON_CHECKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in time.
        /// </summary>
        public static string COLUMN_CHECKIN_TIME {
            get {
                return ResourceManager.GetString("COLUMN_CHECKIN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string COLUMN_QUESTIONNAIRE {
            get {
                return ResourceManager.GetString("COLUMN_QUESTIONNAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string COLUMN_USER_NAME {
            get {
                return ResourceManager.GetString("COLUMN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this check-in?.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in time.
        /// </summary>
        public static string DETAIL_CHECKIN_TIME {
            get {
                return ResourceManager.GetString("DETAIL_CHECKIN_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string DETAIL_NOTE {
            get {
                return ResourceManager.GetString("DETAIL_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string DETAIL_QUESTIONNAIRE {
            get {
                return ResourceManager.GetString("DETAIL_QUESTIONNAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new check-in.
        /// </summary>
        public static string ERROR_CREATE {
            get {
                return ResourceManager.GetString("ERROR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting check-in.
        /// </summary>
        public static string ERROR_DELETE {
            get {
                return ResourceManager.GetString("ERROR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating check-in.
        /// </summary>
        public static string ERROR_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FILTER_ACL_USER {
            get {
                return ResourceManager.GetString("FILTER_ACL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map item.
        /// </summary>
        public static string FILTER_MAP_ITEM {
            get {
                return ResourceManager.GetString("FILTER_MAP_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        public static string FILTER_QUESTIONNAIRE {
            get {
                return ResourceManager.GetString("FILTER_QUESTIONNAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new check-in.
        /// </summary>
        public static string LABEL_CREATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_CREATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of check-in.
        /// </summary>
        public static string LABEL_DETAIL_INFO {
            get {
                return ResourceManager.GetString("LABEL_DETAIL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all check-ins of this map item.
        /// </summary>
        public static string LABEL_LIST_INFO {
            get {
                return ResourceManager.GetString("LABEL_LIST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information about check-in.
        /// </summary>
        public static string LABEL_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete check-in.
        /// </summary>
        public static string MODAL_TITLE_DELETE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new check-in.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in detail.
        /// </summary>
        public static string PAGE_TITLE_DETAIL {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in list.
        /// </summary>
        public static string PAGE_TITLE_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check-in.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose questionnaire....
        /// </summary>
        public static string QUESTIONNAIRE_EMPTY {
            get {
                return ResourceManager.GetString("QUESTIONNAIRE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New check-in has been created.
        /// </summary>
        public static string SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in has been deleted.
        /// </summary>
        public static string SUCCESS_DELETE {
            get {
                return ResourceManager.GetString("SUCCESS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in has been updated.
        /// </summary>
        public static string SUCCESS_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_UPDATE", resourceCulture);
            }
        }
    }
}
