//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCoreModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCoreModel.Localization.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BOOL_VALUE_FALSE {
            get {
                return ResourceManager.GetString("BOOL_VALUE_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BOOL_VALUE_TRUE {
            get {
                return ResourceManager.GetString("BOOL_VALUE_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string BUTTON_ABORT {
            get {
                return ResourceManager.GetString("BUTTON_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BUTTON_BACK {
            get {
                return ResourceManager.GetString("BUTTON_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BUTTON_DELETE {
            get {
                return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string BUTTON_DETAIL {
            get {
                return ResourceManager.GetString("BUTTON_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string BUTTON_HOME {
            get {
                return ResourceManager.GetString("BUTTON_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filter.
        /// </summary>
        public static string BUTTON_RESET_FILTER {
            get {
                return ResourceManager.GetString("BUTTON_RESET_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string BUTTON_SEND {
            get {
                return ResourceManager.GetString("BUTTON_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string COLUMN_ACTION {
            get {
                return ResourceManager.GetString("COLUMN_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting application.
        /// </summary>
        public static string EMAIL_SUBJECT_DEFAULT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating record.
        /// </summary>
        public static string ERROR_CREATE_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CREATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing your request.
        /// </summary>
        public static string ERROR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to enter this section.
        /// </summary>
        public static string ERROR_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested item was not found.
        /// </summary>
        public static string ERROR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fulltext.
        /// </summary>
        public static string FILTER_FULLTEXT {
            get {
                return ResourceManager.GetString("FILTER_FULLTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found.
        /// </summary>
        public static string LABEL_TABLE_EMPTY {
            get {
                return ResourceManager.GetString("LABEL_TABLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count:.
        /// </summary>
        public static string LABEL_TABLE_TOTAL {
            get {
                return ResourceManager.GetString("LABEL_TABLE_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for hunters and stewards.
        /// </summary>
        public static string SUBTITLE_APPLICATION {
            get {
                return ResourceManager.GetString("SUBTITLE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting.
        /// </summary>
        public static string TITLE_APPLICATION {
            get {
                return ResourceManager.GetString("TITLE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        public static string TITLE_SORT_ASC {
            get {
                return ResourceManager.GetString("TITLE_SORT_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        public static string TITLE_SORT_DESC {
            get {
                return ResourceManager.GetString("TITLE_SORT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving changes.
        /// </summary>
        public static string VALIDATION_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("VALIDATION_UPDATE_FAILED", resourceCulture);
            }
        }
    }
}
