//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCoreModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionnaireRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionnaireRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCoreModel.Localization.QuestionnaireRes", typeof(QuestionnaireRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string BUTTON_QUESTION_LIST {
            get {
                return ResourceManager.GetString("BUTTON_QUESTION_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question count.
        /// </summary>
        public static string COLUMN_QUESTION_COUNT {
            get {
                return ResourceManager.GetString("COLUMN_QUESTION_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this questionnaire? All fillings of this questionnaire will be deleted as well..
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DETAIL_DESCRIPTION {
            get {
                return ResourceManager.GetString("DETAIL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire name.
        /// </summary>
        public static string DETAIL_NAME {
            get {
                return ResourceManager.GetString("DETAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new questionnaire.
        /// </summary>
        public static string ERROR_CREATE {
            get {
                return ResourceManager.GetString("ERROR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting questionnaire.
        /// </summary>
        public static string ERROR_DELETE {
            get {
                return ResourceManager.GetString("ERROR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating questionnaire.
        /// </summary>
        public static string ERROR_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new questionnaire.
        /// </summary>
        public static string LABEL_CREATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_CREATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all questionnaires.
        /// </summary>
        public static string LABEL_LIST_INFO {
            get {
                return ResourceManager.GetString("LABEL_LIST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information about questionnaire.
        /// </summary>
        public static string LABEL_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete questionnaire.
        /// </summary>
        public static string MODAL_TITLE_DELETE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new questionnaire.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaires.
        /// </summary>
        public static string PAGE_TITLE_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update questionnaire.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        public static string QUESTION_TYPE_CHECKBOX {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox list.
        /// </summary>
        public static string QUESTION_TYPE_CHECKBOX_LIST {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_CHECKBOX_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option selection.
        /// </summary>
        public static string QUESTION_TYPE_DROPDOWN {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_DROPDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string QUESTION_TYPE_NUMBER {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text area.
        /// </summary>
        public static string QUESTION_TYPE_TEXTAREA {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_TEXTAREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string QUESTION_TYPE_TEXTBOX {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_TEXTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New questionnaire has been created.
        /// </summary>
        public static string SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire has been deleted.
        /// </summary>
        public static string SUCCESS_DELETE {
            get {
                return ResourceManager.GetString("SUCCESS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire has been updated.
        /// </summary>
        public static string SUCCESS_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_UPDATE", resourceCulture);
            }
        }
    }
}
