//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingCoreModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerritoryRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerritoryRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingCoreModel.Localization.TerritoryRes", typeof(TerritoryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact steward.
        /// </summary>
        public static string BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string BUTTON_CONTACT_ACCEPT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string BUTTON_CONTACT_DISMISS {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT_DISMISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create territory.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string BUTTON_INVITE_USER {
            get {
                return ResourceManager.GetString("BUTTON_INVITE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update map item types.
        /// </summary>
        public static string BUTTON_MAP_ITEM_TYPE_LIST {
            get {
                return ResourceManager.GetString("BUTTON_MAP_ITEM_TYPE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        public static string BUTTON_PERSON_LIST {
            get {
                return ResourceManager.GetString("BUTTON_PERSON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save role changes.
        /// </summary>
        public static string BUTTON_SAVE_USER_LIST {
            get {
                return ResourceManager.GetString("BUTTON_SAVE_USER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update map.
        /// </summary>
        public static string BUTTON_UPDATE_MAP {
            get {
                return ResourceManager.GetString("BUTTON_UPDATE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string COLUMN_CONTACT_MESSAGE {
            get {
                return ResourceManager.GetString("COLUMN_CONTACT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string COLUMN_CONTACT_NAME {
            get {
                return ResourceManager.GetString("COLUMN_CONTACT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steward.
        /// </summary>
        public static string COLUMN_STEWARD {
            get {
                return ResourceManager.GetString("COLUMN_STEWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User count.
        /// </summary>
        public static string COLUMN_USER_COUNT {
            get {
                return ResourceManager.GetString("COLUMN_USER_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string COLUMN_USER_EMAIL {
            get {
                return ResourceManager.GetString("COLUMN_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COLUMN_USER_NAME {
            get {
                return ResourceManager.GetString("COLUMN_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string COLUMN_USER_ROLE {
            get {
                return ResourceManager.GetString("COLUMN_USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this user from territory?.
        /// </summary>
        public static string CONFIRM_DELETE_USER {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string DETAIL_CONTACT_MESSAGE {
            get {
                return ResourceManager.GetString("DETAIL_CONTACT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DETAIL_DESCRIPTION {
            get {
                return ResourceManager.GetString("DETAIL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is public?.
        /// </summary>
        public static string DETAIL_IS_PUBLIC {
            get {
                return ResourceManager.GetString("DETAIL_IS_PUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string DETAIL_MAP {
            get {
                return ResourceManager.GetString("DETAIL_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DETAIL_NAME {
            get {
                return ResourceManager.GetString("DETAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while contacting steward.
        /// </summary>
        public static string ERROR_CONTACT {
            get {
                return ResourceManager.GetString("ERROR_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating territory.
        /// </summary>
        public static string ERROR_CREATE {
            get {
                return ResourceManager.GetString("ERROR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing user from this territory.
        /// </summary>
        public static string ERROR_DELETE_USER {
            get {
                return ResourceManager.GetString("ERROR_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating territory.
        /// </summary>
        public static string ERROR_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests for connection.
        /// </summary>
        public static string LABEL_CONTACT_REQUEST {
            get {
                return ResourceManager.GetString("LABEL_CONTACT_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new territory and set you as it&apos;s steward.
        /// </summary>
        public static string LABEL_CREATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_CREATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string LABEL_LEGEND {
            get {
                return ResourceManager.GetString("LABEL_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string LABEL_LEGEND_MAP_AREA {
            get {
                return ResourceManager.GetString("LABEL_LEGEND_MAP_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User locations.
        /// </summary>
        public static string LABEL_LEGEND_USER_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_LEGEND_USER_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User points.
        /// </summary>
        public static string LABEL_LEGEND_USER_POINTS {
            get {
                return ResourceManager.GetString("LABEL_LEGEND_USER_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating map.
        /// </summary>
        public static string LABEL_MAP_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("LABEL_MAP_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map has been successfully updated.
        /// </summary>
        public static string LABEL_MAP_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("LABEL_MAP_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can manage who can access this territory.
        /// </summary>
        public static string LABEL_PERSON_LIST_INFO {
            get {
                return ResourceManager.GetString("LABEL_PERSON_LIST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string LABEL_SAVE_IN_PROGRESS {
            get {
                return ResourceManager.GetString("LABEL_SAVE_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information about territory.
        /// </summary>
        public static string LABEL_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LABEL_USER_EMAIL {
            get {
                return ResourceManager.GetString("LABEL_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LABEL_USER_NAME {
            get {
                return ResourceManager.GetString("LABEL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeding rack.
        /// </summary>
        public static string MAP_ITEM_TYPE_FEEDING {
            get {
                return ResourceManager.GetString("MAP_ITEM_TYPE_FEEDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water pool.
        /// </summary>
        public static string MAP_ITEM_TYPE_POOL {
            get {
                return ResourceManager.GetString("MAP_ITEM_TYPE_POOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New description.
        /// </summary>
        public static string MODAL_RENAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("MODAL_RENAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string MODAL_RENAME_NAME {
            get {
                return ResourceManager.GetString("MODAL_RENAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact territory.
        /// </summary>
        public static string MODAL_TITLE_CONTACT {
            get {
                return ResourceManager.GetString("MODAL_TITLE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user from this territory.
        /// </summary>
        public static string MODAL_TITLE_DELETE_USER {
            get {
                return ResourceManager.GetString("MODAL_TITLE_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string MODAL_TITLE_INVITE_USER {
            get {
                return ResourceManager.GetString("MODAL_TITLE_INVITE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename item.
        /// </summary>
        public static string MODAL_TITLE_RENAME {
            get {
                return ResourceManager.GetString("MODAL_TITLE_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new territory.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory detail.
        /// </summary>
        public static string PAGE_TITLE_DETAIL {
            get {
                return ResourceManager.GetString("PAGE_TITLE_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public territory list.
        /// </summary>
        public static string PAGE_TITLE_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user list.
        /// </summary>
        public static string PAGE_TITLE_PERSON_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_PERSON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update territory.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update map.
        /// </summary>
        public static string PAGE_TITLE_UPDATE_MAP {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User point.
        /// </summary>
        public static string PAGE_TITLE_USER_POINT {
            get {
                return ResourceManager.GetString("PAGE_TITLE_USER_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area .
        /// </summary>
        public static string PREFIX_AREA {
            get {
                return ResourceManager.GetString("PREFIX_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory steward has been contacted.
        /// </summary>
        public static string SUCCESS_CONTACT {
            get {
                return ResourceManager.GetString("SUCCESS_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New territory has been created.
        /// </summary>
        public static string SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been removed from this territory.
        /// </summary>
        public static string SUCCESS_DELETE_USER {
            get {
                return ResourceManager.GetString("SUCCESS_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory has been updated.
        /// </summary>
        public static string SUCCESS_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string TERRITORY_USER_ROLE_EDITOR {
            get {
                return ResourceManager.GetString("TERRITORY_USER_ROLE_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string TERRITORY_USER_ROLE_INVITED {
            get {
                return ResourceManager.GetString("TERRITORY_USER_ROLE_INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string TERRITORY_USER_ROLE_MEMBER {
            get {
                return ResourceManager.GetString("TERRITORY_USER_ROLE_MEMBER", resourceCulture);
            }
        }
    }
}
