//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingModel.Localization.AccountRes", typeof(AccountRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ACCOUNT_TYPE_ADMIN {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string ACCOUNT_TYPE_DEMO {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string ACCOUNT_TYPE_PAYING {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_PAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ACCOUNT_TYPE_STANDARD {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string BUTTON_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string BUTTON_CONFIRM {
            get {
                return ResourceManager.GetString("BUTTON_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string BUTTON_DEMO_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_DEMO_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string BUTTON_FORGOTTEN_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_FORGOTTEN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string BUTTON_LOGIN_LINK {
            get {
                return ResourceManager.GetString("BUTTON_LOGIN_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string BUTTON_LOGOFF {
            get {
                return ResourceManager.GetString("BUTTON_LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string BUTTON_MANAGE {
            get {
                return ResourceManager.GetString("BUTTON_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string BUTTON_REGISTER_LINK {
            get {
                return ResourceManager.GetString("BUTTON_REGISTER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string DETAIL_CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("DETAIL_CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string DETAIL_EMAIL {
            get {
                return ResourceManager.GetString("DETAIL_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string DETAIL_PASSWORD {
            get {
                return ResourceManager.GetString("DETAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string DETAIL_REMEMBER_ME {
            get {
                return ResourceManager.GetString("DETAIL_REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email code is invalid or expired.
        /// </summary>
        public static string ERROR_CODE_INVALID {
            get {
                return ResourceManager.GetString("ERROR_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not allowed for administrator account. Please contact developer..
        /// </summary>
        public static string ERROR_FORGOTTEN_PASSWORD_ADMIN {
            get {
                return ResourceManager.GetString("ERROR_FORGOTTEN_PASSWORD_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while login.
        /// </summary>
        public static string ERROR_LOGIN_DEMO {
            get {
                return ResourceManager.GetString("ERROR_LOGIN_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 and 30 characters long.
        /// </summary>
        public static string LABEL_CHANGE_PASSWORD_INFO {
            get {
                return ResourceManager.GetString("LABEL_CHANGE_PASSWORD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email address and set your password. Password must be between 8 and 30 characters long.
        /// </summary>
        public static string LABEL_CONFIRM_INFO {
            get {
                return ResourceManager.GetString("LABEL_CONFIRM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new password. Password must be between 8 and 30 characters long.
        /// </summary>
        public static string LABEL_FORGOTTEN_PASSWORD_CONFIRM_INFO {
            get {
                return ResourceManager.GetString("LABEL_FORGOTTEN_PASSWORD_CONFIRM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address. If such account exists, email will be sent to it..
        /// </summary>
        public static string LABEL_FORGOTTEN_PASSWORD_INFO {
            get {
                return ResourceManager.GetString("LABEL_FORGOTTEN_PASSWORD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}!.
        /// </summary>
        public static string LABEL_HELLO_FORMAT {
            get {
                return ResourceManager.GetString("LABEL_HELLO_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string LABEL_LOCKOUT_LINE1 {
            get {
                return ResourceManager.GetString("LABEL_LOCKOUT_LINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LABEL_LOCKOUT_LINE2 {
            get {
                return ResourceManager.GetString("LABEL_LOCKOUT_LINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error..
        /// </summary>
        public static string LABEL_LOGIN_ERROR_LINE1 {
            get {
                return ResourceManager.GetString("LABEL_LOGIN_ERROR_LINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during logon, please try again later..
        /// </summary>
        public static string LABEL_LOGIN_ERROR_LINE2 {
            get {
                return ResourceManager.GetString("LABEL_LOGIN_ERROR_LINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string LABEL_LOGIN_INFO {
            get {
                return ResourceManager.GetString("LABEL_LOGIN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Error..
        /// </summary>
        public static string LABEL_REGISTER_ERROR_LINE1 {
            get {
                return ResourceManager.GetString("LABEL_REGISTER_ERROR_LINE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during registration, please try again later..
        /// </summary>
        public static string LABEL_REGISTER_ERROR_LINE2 {
            get {
                return ResourceManager.GetString("LABEL_REGISTER_ERROR_LINE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string LABEL_REGISTER_INFO {
            get {
                return ResourceManager.GetString("LABEL_REGISTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited.
        /// </summary>
        public static string LABEL_TERRITORY_COUNT_UNLIMITED {
            get {
                return ResourceManager.GetString("LABEL_TERRITORY_COUNT_UNLIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string PAGE_TITLE_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email address.
        /// </summary>
        public static string PAGE_TITLE_CONFIRM {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string PAGE_TITLE_FORGOTTEN_PASSWORD {
            get {
                return ResourceManager.GetString("PAGE_TITLE_FORGOTTEN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string PAGE_TITLE_FORGOTTEN_PASSWORD_CONFIRM {
            get {
                return ResourceManager.GetString("PAGE_TITLE_FORGOTTEN_PASSWORD_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string PAGE_TITLE_LOCKOUT {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LOCKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string PAGE_TITLE_LOGIN {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string PAGE_TITLE_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage account.
        /// </summary>
        public static string PAGE_TITLE_MANAGE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string PAGE_TITLE_REGISTER {
            get {
                return ResourceManager.GetString("PAGE_TITLE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Error.
        /// </summary>
        public static string PAGE_TITLE_REGISTER_ERROR {
            get {
                return ResourceManager.GetString("PAGE_TITLE_REGISTER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill in your email address.
        /// </summary>
        public static string REQUIRED_FORGOTTEN_EMAIL {
            get {
                return ResourceManager.GetString("REQUIRED_FORGOTTEN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been activated.
        /// </summary>
        public static string SUCCESS_CONFIRM {
            get {
                return ResourceManager.GetString("SUCCESS_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If requested account exists, new email has been sent to you.
        /// </summary>
        public static string SUCCESS_FORGOTTEN_PASSWORD {
            get {
                return ResourceManager.GetString("SUCCESS_FORGOTTEN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as Demo user.
        /// </summary>
        public static string SUCCESS_LOGIN_DEMO {
            get {
                return ResourceManager.GetString("SUCCESS_LOGIN_DEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string SUCCESS_PASSWORD_CHANGED {
            get {
                return ResourceManager.GetString("SUCCESS_PASSWORD_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string VALIDATION_LOGIN_INVALID {
            get {
                return ResourceManager.GetString("VALIDATION_LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already used..
        /// </summary>
        public static string VALIDATION_REGISTER_USED {
            get {
                return ResourceManager.GetString("VALIDATION_REGISTER_USED", resourceCulture);
            }
        }
    }
}
