//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingModel.Localization.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        public static string BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string BUTTON_BACK {
            get {
                return ResourceManager.GetString("BUTTON_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit heslo.
        /// </summary>
        public static string BUTTON_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("BUTTON_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úvod.
        /// </summary>
        public static string BUTTON_HOME {
            get {
                return ResourceManager.GetString("BUTTON_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string BUTTON_PAGE_FIRST {
            get {
                return ResourceManager.GetString("BUTTON_PAGE_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string BUTTON_PAGE_LAST {
            get {
                return ResourceManager.GetString("BUTTON_PAGE_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string BUTTON_PAGE_NEXT {
            get {
                return ResourceManager.GetString("BUTTON_PAGE_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string BUTTON_PAGE_PREV {
            get {
                return ResourceManager.GetString("BUTTON_PAGE_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strana:.
        /// </summary>
        public static string LABEL_PAGER {
            get {
                return ResourceManager.GetString("LABEL_PAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítej {0}!.
        /// </summary>
        public static string LABEL_WELCOME {
            get {
                return ResourceManager.GetString("LABEL_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikace pro lovce a správce revírů.
        /// </summary>
        public static string SUBTITLE_APPLICATION {
            get {
                return ResourceManager.GetString("SUBTITLE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting.
        /// </summary>
        public static string TITLE_APPLICATION {
            get {
                return ResourceManager.GetString("TITLE_APPLICATION", resourceCulture);
            }
        }
    }
}
