//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingModel.Localization.HomeRes", typeof(HomeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited territories.
        /// </summary>
        public static string LABEL_HUNTER {
            get {
                return ResourceManager.GetString("LABEL_HUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by contacting a steward or write us to upgrade your account..
        /// </summary>
        public static string LABEL_START_FREE {
            get {
                return ResourceManager.GetString("LABEL_START_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to try our application, please use login screen and click the &quot;Demo&quot; button. If you are a registered user, please log in..
        /// </summary>
        public static string LABEL_START_LOGIN {
            get {
                return ResourceManager.GetString("LABEL_START_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by creating new territory or contacting a steward.
        /// </summary>
        public static string LABEL_START_PAYED {
            get {
                return ResourceManager.GetString("LABEL_START_PAYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stewarded territories:.
        /// </summary>
        public static string LABEL_STEWARD {
            get {
                return ResourceManager.GetString("LABEL_STEWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string PAGE_TITLE_ABOUT {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string PAGE_TITLE_HOME {
            get {
                return ResourceManager.GetString("PAGE_TITLE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territories.
        /// </summary>
        public static string TITLE_TERRITORY {
            get {
                return ResourceManager.GetString("TITLE_TERRITORY", resourceCulture);
            }
        }
    }
}
