//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuestionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingModel.Localization.QuestionRes", typeof(QuestionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string COLUMN_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLUMN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string COLUMN_OPTION_NAME {
            get {
                return ResourceManager.GetString("COLUMN_OPTION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string COLUMN_TYPE {
            get {
                return ResourceManager.GetString("COLUMN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this question?.
        /// </summary>
        public static string CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DETAIL_DESCRIPTION {
            get {
                return ResourceManager.GetString("DETAIL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is required?.
        /// </summary>
        public static string DETAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("DETAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string DETAIL_NAME {
            get {
                return ResourceManager.GetString("DETAIL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string DETAIL_QUESTION_TYPE {
            get {
                return ResourceManager.GetString("DETAIL_QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new question.
        /// </summary>
        public static string ERROR_CREATE {
            get {
                return ResourceManager.GetString("ERROR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting question.
        /// </summary>
        public static string ERROR_DELETE {
            get {
                return ResourceManager.GetString("ERROR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while moving question.
        /// </summary>
        public static string ERROR_MOVE {
            get {
                return ResourceManager.GetString("ERROR_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating question.
        /// </summary>
        public static string ERROR_UPDATE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new question.
        /// </summary>
        public static string LABEL_CREATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_CREATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all questions in current questionnaire.
        /// </summary>
        public static string LABEL_LIST_INFO {
            get {
                return ResourceManager.GetString("LABEL_LIST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information about question.
        /// </summary>
        public static string LABEL_UPDATE_INFO {
            get {
                return ResourceManager.GetString("LABEL_UPDATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete question.
        /// </summary>
        public static string MODAL_TITLE_DELETE {
            get {
                return ResourceManager.GetString("MODAL_TITLE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new question.
        /// </summary>
        public static string PAGE_TITLE_CREATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string PAGE_TITLE_LIST {
            get {
                return ResourceManager.GetString("PAGE_TITLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update question.
        /// </summary>
        public static string PAGE_TITLE_UPDATE {
            get {
                return ResourceManager.GetString("PAGE_TITLE_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New question has been created.
        /// </summary>
        public static string SUCCESS_CREATE {
            get {
                return ResourceManager.GetString("SUCCESS_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been deleted.
        /// </summary>
        public static string SUCCESS_DELETE {
            get {
                return ResourceManager.GetString("SUCCESS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been updated.
        /// </summary>
        public static string SUCCESS_UPDATE {
            get {
                return ResourceManager.GetString("SUCCESS_UPDATE", resourceCulture);
            }
        }
    }
}
