//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerritoryRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerritoryRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingModel.Localization.TerritoryRes", typeof(TerritoryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový krmelec.
        /// </summary>
        public static string BUTTON_APPEND_FEEDING_PLACE {
            get {
                return ResourceManager.GetString("BUTTON_APPEND_FEEDING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat novou oblast.
        /// </summary>
        public static string BUTTON_APPEND_HUNTING_GROUND {
            get {
                return ResourceManager.GetString("BUTTON_APPEND_HUNTING_GROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat nový posed.
        /// </summary>
        public static string BUTTON_APPEND_SHOOTING_PLACE {
            get {
                return ResourceManager.GetString("BUTTON_APPEND_SHOOTING_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktovat správce revíru.
        /// </summary>
        public static string BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založit revír.
        /// </summary>
        public static string BUTTON_CREATE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit mapu.
        /// </summary>
        public static string BUTTON_EDIT_MAP {
            get {
                return ResourceManager.GetString("BUTTON_EDIT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam revírů.
        /// </summary>
        public static string BUTTON_LIST {
            get {
                return ResourceManager.GetString("BUTTON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat.
        /// </summary>
        public static string BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit.
        /// </summary>
        public static string BUTTON_SHOW {
            get {
                return ResourceManager.GetString("BUTTON_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k chybě při ukládání revíru. Akce nebyla provdena..
        /// </summary>
        public static string ERROR_CREATE {
            get {
                return ResourceManager.GetString("ERROR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string HEADER_LIST_NAME {
            get {
                return ResourceManager.GetString("HEADER_LIST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string LABEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LABEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krmelce.
        /// </summary>
        public static string LABEL_FEEDING_PLACES {
            get {
                return ResourceManager.GetString("LABEL_FEEDING_PLACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblasti.
        /// </summary>
        public static string LABEL_HUNTING_GROUNDS {
            get {
                return ResourceManager.GetString("LABEL_HUNTING_GROUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo k chybě při ukládání .
        /// </summary>
        public static string LABEL_MAP_UPDATE_FAIL {
            get {
                return ResourceManager.GetString("LABEL_MAP_UPDATE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukládání proběhlo úspěšně.
        /// </summary>
        public static string LABEL_MAP_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("LABEL_MAP_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string LABEL_NAME {
            get {
                return ResourceManager.GetString("LABEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukládá se....
        /// </summary>
        public static string LABEL_SAVE_IN_PROGRESS {
            get {
                return ResourceManager.GetString("LABEL_SAVE_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posedy.
        /// </summary>
        public static string LABEL_SHOOTING_PLACES {
            get {
                return ResourceManager.GetString("LABEL_SHOOTING_PLACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krmelec .
        /// </summary>
        public static string NEW_FEEDING_PLACE_NAME {
            get {
                return ResourceManager.GetString("NEW_FEEDING_PLACE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblast .
        /// </summary>
        public static string NEW_HUNTING_GROUND_NAME {
            get {
                return ResourceManager.GetString("NEW_HUNTING_GROUND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posed .
        /// </summary>
        public static string NEW_SHOOTING_PLACE_NAME {
            get {
                return ResourceManager.GetString("NEW_SHOOTING_PLACE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hledat.
        /// </summary>
        public static string PLACEHOLDER_SEARCH {
            get {
                return ResourceManager.GetString("PLACEHOLDER_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoří nový revír a nastaví vás jako jeho správce..
        /// </summary>
        public static string SUBTITLE_CREATE {
            get {
                return ResourceManager.GetString("SUBTITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Založit revír.
        /// </summary>
        public static string TITLE_CREATE {
            get {
                return ResourceManager.GetString("TITLE_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spravované revíry.
        /// </summary>
        public static string TITLE_LIST {
            get {
                return ResourceManager.GetString("TITLE_LIST", resourceCulture);
            }
        }
    }
}
