//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string StringValue { get; set; }
        public Nullable<double> FloatValue { get; set; }
        public Nullable<int> IntValue { get; set; }
        public Nullable<bool> BoolValue { get; set; }
        public Nullable<int> OptionId { get; set; }
        public int CheckInId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Option Option { get; set; }
        public virtual Question Question { get; set; }
    }
}
