//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    
    public partial class CheckInListItem
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string QuestionnaireName { get; set; }
        public System.DateTime CheckInTime { get; set; }
    }
}
