//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailInfo
    {
        public int Id { get; set; }
        public string SenderAddress { get; set; }
        public string ReceiverAddress { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime SysCreated { get; set; }
        public int SysCreator { get; set; }
        public int RetryCount { get; set; }
        public int SendState { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SysEditor { get; set; }
        public Nullable<System.DateTime> SysUpdated { get; set; }
    }
}
