//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuntingEntities : DbContext
    {
        public HuntingEntities()
            : base("name=HuntingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AclUser> AclUsers { get; set; }
        public virtual DbSet<EmailInfo> EmailInfoes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MapItem> MapItems { get; set; }
        public virtual DbSet<MapItemType> MapItemTypes { get; set; }
        public virtual DbSet<ModelVersion> ModelVersions { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<TerritoryUser> TerritoryUsers { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<UserMapPoint> UserMapPoints { get; set; }
        public virtual DbSet<UserMapPointShare> UserMapPointShares { get; set; }
        public virtual DbSet<MapArea> MapAreas { get; set; }
        public virtual DbSet<TerritoryUserContact> TerritoryUserContacts { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Questionnaire> Questionnaires { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<CheckIn> CheckIns { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
    }
}
