//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public bool IsDeleted { get; set; }
        public string Shortcut { get; set; }
        public bool IsDefault { get; set; }
        public string DateFormat { get; set; }
        public string TimeFormat { get; set; }
        public string DateFormatJS { get; set; }
        public string TimeFormatJS { get; set; }
    }
}
