//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapItem()
        {
            this.CheckIns = new HashSet<CheckIn>();
        }
    
        public int Id { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public string Name { get; set; }
        public int MapItemType { get; set; }
        public int TerritoryId { get; set; }
        public int SysCreator { get; set; }
        public System.DateTime SysCreated { get; set; }
        public Nullable<int> SysEditor { get; set; }
        public Nullable<System.DateTime> SysUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual AclUser AclUser { get; set; }
        public virtual AclUser AclUser1 { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual MapItemType MapItemTypeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckIn> CheckIns { get; set; }
    }
}
