//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    
    public partial class TerritoryListItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserCount { get; set; }
        public string Steward { get; set; }
        public int ContactCount { get; set; }
    }
}
