//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public int Id { get; set; }
        public string Session { get; set; }
        public int AclUserId { get; set; }
        public System.DateTime SysCreated { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AclUser AclUser { get; set; }
    }
}
