//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocation
    {
        public int Id { get; set; }
        public int SysCreator { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public System.DateTime SysCreated { get; set; }
        public int TrackId { get; set; }
    
        public virtual AclUser AclUser { get; set; }
        public virtual Track Track { get; set; }
    }
}
