//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuntingEntities : DbContext
    {
        public HuntingEntities()
            : base("name=HuntingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ModelVersion> ModelVersions { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<HunterUser> HunterUsers { get; set; }
        public virtual DbSet<TerritoryUser> TerritoryUsers { get; set; }
        public virtual DbSet<HuntingGround> HuntingGrounds { get; set; }
        public virtual DbSet<MapItem> MapItems { get; set; }
    }
}
