//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapItem
    {
        public int Id { get; set; }
        public double LocationX { get; set; }
        public double LocationY { get; set; }
        public string Name { get; set; }
        public int MapItemType { get; set; }
        public int TerritoryId { get; set; }
    
        public virtual Territory Territory { get; set; }
    }
}
