//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        public Territory()
        {
            this.TerritoryUsers = new HashSet<TerritoryUser>();
            this.HuntingGrounds = new HashSet<HuntingGround>();
            this.MapItems = new HashSet<MapItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string StewardId { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual HunterUser HunterUser { get; set; }
        public virtual ICollection<TerritoryUser> TerritoryUsers { get; set; }
        public virtual ICollection<HuntingGround> HuntingGrounds { get; set; }
        public virtual ICollection<MapItem> MapItems { get; set; }
    }
}
